const redirects = new Map([
  ["resource", "/classes/Resource"],
  ["tableofcontents", "/classes/TableOfContents"],
  ["tableofcontentsentry", "/classes/TableOfContentsEntry"],
  ["course", "/classes/Course"],
  ["coursesection", "/classes/CourseSection"],
  ["coursesyllabus", "/classes/CourseSyllabus"],
  ["topic", "/classes/Topic"],
  ["classstanding", "/classes/ClassStanding"],
  ["learningcomponent", "/classes/LearningComponent"],
  ["learningobjective", "/classes/LearningObjective"],
  ["associatedmaterial", "/classes/AssociatedMaterial"],
  ["supportingmaterial", "/classes/SupportingMaterial"],
  ["supplementalmaterial", "/classes/SupplementalMaterial"],
  ["referencedmaterial", "/classes/ReferencedMaterial"],
  ["instructionalpattern", "/classes/InstructionalPattern"],
  ["lesson", "/classes/Lesson"],
  ["unit", "/classes/Unit"],
  ["module", "/classes/Module"],
  ["assessment", "/classes/Assessment"],
  ["quiz", "/classes/Quiz"],
  ["submission", "/classes/Submission"],
  ["rubric", "/classes/Rubric"],
  ["rubriccriterion", "/classes/RubricCriterion"],
  ["rubricscale", "/classes/RubricScale"],
  ["rubriclevel", "/classes/RubricLevel"],
  ["task", "/classes/Task"],
  ["activity", "/classes/Activity"],
  ["project", "/classes/Project"],
  ["practice", "/classes/Practice"],
  ["format", "/classes/Format"],
  ["facetofaceformat", "/classes/FaceToFaceFormat"],
  ["gradeformat", "/classes/GradeFormat"],
  ["pointgradeformat", "/classes/PointGradeFormat"],
  ["lettergradeformat", "/classes/LetterGradeFormat"],
  ["percentgradeformat", "/classes/PercentGradeFormat"],
  ["completiongradeformat", "/classes/CompletionGradeFormat"],
  ["thing", "/classes/Thing"],
  ["intangible", "/classes/Intangible"],
  ["class", "/classes/Class"],
  ["property", "/classes/Property"],
  ["enumeration", "/classes/Enumeration"],
  ["datatype", "/classes/DataType"],
  ["person", "/classes/Person"],
  ["organization", "/classes/Organization"],
  ["place", "/classes/Place"],
  ["structuredvalue", "/classes/StructuredValue"],
  ["creativework", "/classes/CreativeWork"],
  ["mediaobject", "/classes/MediaObject"],
  ["imageobject", "/classes/ImageObject"],
  ["boolean", "/classes/Boolean"],
  ["date", "/classes/Date"],
  ["datetime", "/classes/DateTime"],
  ["integer", "/classes/Integer"],
  ["number", "/classes/Number"],
  ["text", "/classes/Text"],
  ["time", "/classes/Time"],
  ["url", "/classes/URL"],
  ["yes", "/classes/Yes"],
  ["no", "/classes/No"],
  ["true", "/classes/True"],
  ["false", "/classes/False"],
  ["actiontype", "/classes/ActionType"],
  ["writing", "/classes/Writing"],
  ["reading", "/classes/Reading"],
  ["making", "/classes/Making"],
  ["researching", "/classes/Researching"],
  ["listening", "/classes/Listening"],
  ["watching", "/classes/Watching"],
  ["reflecting", "/classes/Reflecting"],
  ["discussing", "/classes/Discussing"],
  ["observing", "/classes/Observing"],
  ["presenting", "/classes/Presenting"],
  ["assess", "/classes/Assess"],
  ["entry", "/properties/entry"],
  ["name", "/properties/name"],
  ["additionalname", "/properties/additionalName"],
  ["additionaltype", "/properties/additionalType"],
  ["description", "/properties/description"],
  ["image", "/properties/image"],
  ["mainentityofpage", "/properties/mainEntityOfPage"],
  ["sameas", "/properties/sameAs"],
  ["uri", "/properties/uri"],
  ["rangeincludes", "/properties/rangeIncludes"],
  ["domainincludes", "/properties/domainIncludes"],
  ["supersededby", "/properties/supersededBy"],
  ["inverseof", "/properties/inverseOf"],
  ["courseidentifier", "/properties/courseIdentifier"],
  ["sectionidentifier", "/properties/sectionIdentifier"],
  ["primaryinstructor", "/properties/primaryInstructor"],
  ["instructor", "/properties/instructor"],
  ["courseprerequisites", "/properties/coursePrerequisites"],
  ["institution", "/properties/institution"],
  ["department", "/properties/department"],
  ["program", "/properties/program"],
  ["syllabus", "/properties/syllabus"],
  ["currentstanding", "/properties/currentStanding"],
  ["deliverymode", "/properties/deliveryMode"],
  ["enrollmentsize", "/properties/enrollmentSize"],
  ["haslearningobjective", "/properties/hasLearningObjective"],
  ["forcourse", "/properties/forCourse"],
  ["section", "/properties/section"],
  ["termoffered", "/properties/termOffered"],
  ["parentof", "/properties/parentOf"],
  ["childof", "/properties/childOf"],
  ["maincontent", "/properties/mainContent"],
  ["deliveryformat", "/properties/deliveryFormat"],
  ["material", "/properties/material"],
  ["assessing", "/properties/assessing"],
  ["rubric", "/properties/rubric"],
  ["assessedby", "/properties/assessedBy"],
  ["gradingformat", "/properties/gradingFormat"],
  ["skill", "/properties/skill"],
  ["forcomponent", "/properties/forComponent"],
  ["hascomponent", "/properties/hasComponent"],
  ["dotask", "/properties/doTask"],
  ["typeofaction", "/properties/typeOfAction"],
  ["fortopic", "/properties/forTopic"],
  ["associatedmedia", "/properties/associatedMedia"],
  ["hascriterion", "/properties/hasCriterion"],
  ["rubricscale", "/properties/rubricScale"],
  ["rubrictype", "/properties/rubricType"],
  ["criterionweight", "/properties/criterionWeight"],
  ["haslevel", "/properties/hasLevel"],
  ["levelordinal", "/properties/levelOrdinal"],
  ["levelpoints", "/properties/levelPoints"],
  ["pointsrequired", "/properties/pointsRequired"]
]);

export default function middleware(request) {
  const { pathname } = new URL(request.url);
  const trimmed = pathname.endsWith("/") ? pathname.slice(0, -1) : pathname;
  const key = trimmed.startsWith("/") ? trimmed.slice(1).toLowerCase() : trimmed.toLowerCase();
  const target = redirects.get(key);

  if (target) {
    return Response.redirect(target, 308);
  }

  return undefined;
}